export type CityGuide = {
  slug: string;
  name: string;
  departmentSlug: string;
  departmentName: string;
  intro: string;
  idealFor: string;
  nearby: string[];
  practical: string[];
};

const guides: CityGuide[] = [
  { slug: "frejus", name: "Fréjus", departmentSlug: "var", departmentName: "Var", intro: "Entre plages, centre historique et grands campings, Fréjus est une base familiale complète sur la Côte d’Azur.", idealFor: "Les familles qui veulent des parcs aquatiques, des animations et beaucoup de sorties à proximité.", nearby: ["Base nature François-Léotard", "Port-Fréjus", "Massif de l’Estérel"], practical: ["Comparer la distance réelle jusqu’à la plage", "Anticiper la circulation en juillet-août", "Vérifier navettes et stationnement du camping"] },
  { slug: "saint-aygulf", name: "Saint-Aygulf", departmentSlug: "var", departmentName: "Var", intro: "Le quartier littoral de Fréjus séduit par ses plages, ses étangs et son ambiance de station familiale.", idealFor: "Ceux qui souhaitent rester proches de la mer tout en profitant des équipements de Fréjus.", nearby: ["Plage de Saint-Aygulf", "Étangs de Villepey", "Calanques du sentier du littoral"], practical: ["Circulation dense en été", "Prévoir un anti-moustiques près des étangs", "Vérifier si une navette plage est incluse"] },
  { slug: "saint-raphael", name: "Saint-Raphaël", departmentSlug: "var", departmentName: "Var", intro: "Une ville balnéaire entre le golfe de Fréjus et les roches rouges de l’Estérel.", idealFor: "Les voyageurs qui veulent conjuguer plages, ville animée et randonnées dans l’Estérel.", nearby: ["Vieux-Port", "Plage du Veillat", "Corniche d’Or"], practical: ["Le stationnement est tendu en saison", "Train pratique entre plusieurs stations", "Partir tôt pour les randonnées estivales"] },
  { slug: "agay", name: "Agay", departmentSlug: "var", departmentName: "Var", intro: "Une baie entourée par l’Estérel, connue pour son décor rouge et bleu spectaculaire.", idealFor: "Les amoureux de nature, de criques et de randonnée qui acceptent d’être un peu à l’écart.", nearby: ["Baie d’Agay", "Cap Dramont", "Pic de l’Ours"], practical: ["Voiture utile pour rayonner", "Routes côtières chargées en été", "Respecter les restrictions d’accès aux massifs"] },
  { slug: "roquebrune-sur-argens", name: "Roquebrune-sur-Argens", departmentSlug: "var", departmentName: "Var", intro: "Entre village provençal, rocher de Roquebrune et plages des Issambres, la commune offre plusieurs ambiances.", idealFor: "Les familles recherchant davantage de calme avec mer et arrière-pays accessibles en voiture.", nearby: ["Rocher de Roquebrune", "Les Issambres", "Gorges du Blavet"], practical: ["La commune est très étendue", "Voiture presque indispensable", "Bien vérifier le quartier exact du camping"] },
  { slug: "penmarch", name: "Penmarch", departmentSlug: "finistere", departmentName: "Finistère", intro: "Une base très maritime au cœur du Pays Bigouden, entre ports, phares et longues plages.", idealFor: "Les familles qui aiment l’océan, les balades côtières et les vacances sans chichi.", nearby: ["Phare d’Eckmühl", "Plage du Ster", "Port de Saint-Guénolé"], practical: ["Prévoir un coupe-vent même en été", "Vérifier la distance à pied jusqu’à la plage", "Marchés et commerces accessibles dans la commune"] },
  { slug: "quimper", name: "Quimper", departmentSlug: "finistere", departmentName: "Finistère", intro: "Une ville d’art et d’histoire pratique pour rayonner dans tout le sud Finistère.", idealFor: "Ceux qui veulent alterner patrimoine, restaurants et excursions vers la côte.", nearby: ["Cathédrale Saint-Corentin", "Locronan", "Baie de Douarnenez"], practical: ["La mer nécessite un trajet en voiture", "Le centre se visite facilement à pied", "Bonne base les jours de météo changeante"] },
  { slug: "fouesnant", name: "Fouesnant", departmentSlug: "finistere", departmentName: "Finistère", intro: "Plages, criques et sentiers côtiers face à l’archipel des Glénan.", idealFor: "Les amateurs de baignade, de voile et de paysages bretons lumineux.", nearby: ["Beg-Meil", "Cap-Coz", "Archipel des Glénan"], practical: ["Réserver les traversées vers les Glénan", "Vérifier la présence d’une piscine couverte", "Le vélo facilite les petits déplacements"] },
  { slug: "benodet", name: "Bénodet", departmentSlug: "finistere", departmentName: "Finistère", intro: "Une station familiale à l’embouchure de l’Odet, avec plage, port et promenades.", idealFor: "Les familles recherchant une station animée et des services à proximité.", nearby: ["Plage du Trez", "Rivière de l’Odet", "Sainte-Marine"], practical: ["La station est fréquentée en juillet-août", "Comparer accès plage et accès piscine", "Excursions possibles en bateau"] },
  { slug: "les-mathes", name: "Les Mathes", departmentSlug: "charente-maritime", departmentName: "Charente-Maritime", intro: "Entre la forêt de la Coubre et La Palmyre, Les Mathes concentre de grands campings familiaux proches des plages atlantiques.", idealFor: "Les familles qui recherchent des parcs aquatiques, des pistes cyclables et de nombreuses activités autour de La Palmyre.", nearby: ["Zoo de La Palmyre", "Phare de la Coubre", "Baie de Bonne Anse"], practical: ["Vérifier la distance réelle jusqu’à l’océan", "Le vélo est pratique dans la pinède", "Anticiper la circulation vers les plages en août"] },
  { slug: "saint-just-luzac", name: "Saint-Just-Luzac", departmentSlug: "charente-maritime", departmentName: "Charente-Maritime", intro: "Une base paisible entre Rochefort, Marennes et l’île d’Oléron, au cœur des marais de la Seudre.", idealFor: "Les voyageurs qui veulent rayonner entre patrimoine, ostréiculture et plages tout en séjournant dans un grand domaine au calme.", nearby: ["Île d’Oléron", "Cité de l’Huître à Marennes", "Rochefort et l’Hermione"], practical: ["Une voiture est recommandée", "Regrouper les visites par secteur", "Contrôler le temps de trajet jusqu’aux plages"] },
  { slug: "le-bois-plage-en-re", name: "Le Bois-Plage-en-Ré", departmentSlug: "charente-maritime", departmentName: "Charente-Maritime", intro: "Un village central de l’île de Ré avec marché, grande plage de sable et réseau cyclable accessible.", idealFor: "Les familles qui souhaitent laisser la voiture au camping et rejoindre plage, marché et villages voisins à vélo.", nearby: ["Plage du Petit Sergent", "Marché du Bois-Plage", "Saint-Martin-de-Ré"], practical: ["Intégrer le passage du pont au budget", "Réserver les vélos en haute saison", "Vérifier si la piscine est indispensable à votre séjour"] },
  { slug: "saint-sauveur-de-montagut", name: "Saint-Sauveur-de-Montagut", departmentSlug: "ardeche", departmentName: "Ardèche", intro: "Un village de la vallée de l’Eyrieux entouré de reliefs, de rivières et de voies douces.", idealFor: "Les voyageurs qui préfèrent le calme, le vélo et la nature aux grands sites bondés.", nearby: ["Dolce Via", "Vallée de l’Eyrieux", "Les Ollières-sur-Eyrieux"], practical: ["Routes sinueuses à anticiper", "Vélo électrique utile sur certains parcours", "Vérifier les conditions de baignade en rivière"] },
  { slug: "vallon-pont-darc", name: "Vallon-Pont-d’Arc", departmentSlug: "ardeche", departmentName: "Ardèche", intro: "La porte d’entrée des gorges de l’Ardèche et le secteur phare pour le canoë.", idealFor: "Les familles actives qui veulent découvrir les grands paysages ardéchois.", nearby: ["Pont d’Arc", "Grotte Chauvet 2", "Route des gorges"], practical: ["Réserver le canoë en haute saison", "Partir tôt pour éviter la circulation", "Prévoir eau et protection solaire"] },
  { slug: "sampzon", name: "Sampzon", departmentSlug: "ardeche", departmentName: "Ardèche", intro: "Un point de chute naturel près de la rivière et des villages du sud Ardèche.", idealFor: "Ceux qui veulent rester proches des gorges tout en dormant hors du centre de Vallon.", nearby: ["Rocher de Sampzon", "Ruoms", "Gorges de l’Ardèche"], practical: ["Voiture conseillée pour les visites", "Contrôler l’accès réel à la rivière", "Climatisation appréciable en été"] },
  { slug: "privas", name: "Privas", departmentSlug: "ardeche", departmentName: "Ardèche", intro: "Une petite ville centrale pour découvrir une Ardèche plus calme et gourmande.", idealFor: "Les couples et familles recherchant marchés, balades et position centrale.", nearby: ["Montoulon", "Vallée de l’Ouvèze", "Villages de l’Ardèche centrale"], practical: ["Plus éloignée des gorges", "Commerces utiles pour un séjour autonome", "Bon point de départ pour rayonner"] },
  { slug: "atur", name: "Atur", departmentSlug: "dordogne", departmentName: "Dordogne", intro: "Aux portes de Périgueux, une base verte pour explorer le Périgord central.", idealFor: "Les familles qui souhaitent conjuguer grand camping, patrimoine et services urbains.", nearby: ["Périgueux", "Cathédrale Saint-Front", "Musée Vesunna"], practical: ["Voiture nécessaire pour rayonner", "Périgueux est rapidement accessible", "Regrouper les visites par secteur"] },
  { slug: "saint-crepin-et-carlucet", name: "Saint-Crépin-et-Carlucet", departmentSlug: "dordogne", departmentName: "Dordogne", intro: "Un village du Périgord Noir bien placé entre Sarlat et les sites de la Vézère.", idealFor: "Les passionnés de villages, de châteaux et de préhistoire.", nearby: ["Sarlat-la-Canéda", "Jardins d’Eyrignac", "Lascaux IV"], practical: ["Partir tôt vers Sarlat en été", "Petites routes parfois lentes", "Réserver les grands sites à l’avance"] },
  { slug: "saint-martial-de-nabirat", name: "Saint-Martial-de-Nabirat", departmentSlug: "dordogne", departmentName: "Dordogne", intro: "Une campagne paisible au sud du Périgord Noir, proche de la vallée de la Dordogne.", idealFor: "Les familles voulant du calme entre deux journées de visites.", nearby: ["Domme", "La Roque-Gageac", "Gourdon"], practical: ["Commerces limités dans le village", "Voiture indispensable", "Prévoir les temps de trajet vers les sites"] },
  { slug: "saint-andre-dallas", name: "Saint-André-d’Allas", departmentSlug: "dordogne", departmentName: "Dordogne", intro: "Un emplacement rural à quelques kilomètres de Sarlat et des châteaux de la Dordogne.", idealFor: "Les voyageurs qui privilégient la tranquillité et la proximité de Sarlat.", nearby: ["Sarlat-la-Canéda", "Château de Beynac", "Vallée de la Dordogne"], practical: ["Accès en voiture recommandé", "Acheter les provisions avant le retour au camping", "Alterner visites et journées de repos"] },
  { slug: "patornay", name: "Patornay", departmentSlug: "jura", departmentName: "Jura", intro: "Au bord de l’Ain, une base pratique au centre de la région des lacs.", idealFor: "Les familles attirées par les rivières, les lacs et les activités de pleine nature.", nearby: ["Lac de Vouglans", "Clairvaux-les-Lacs", "Cascades du Hérisson"], practical: ["Voiture utile pour changer de lac", "Soirées parfois fraîches", "Chaussures adaptées aux sentiers"] },
  { slug: "chatillon", name: "Châtillon", departmentSlug: "jura", departmentName: "Jura", intro: "Un village calme et boisé à proximité des principaux lacs jurassiens.", idealFor: "Ceux qui veulent se reposer dans la nature sans s’éloigner des excursions.", nearby: ["Lac de Chalain", "Baume-les-Messieurs", "Cascades du Hérisson"], practical: ["Peu de commerces accessibles à pied", "Prévoir les courses à l’avance", "Équipement de pluie conseillé"] },
  { slug: "clairvaux-les-lacs", name: "Clairvaux-les-Lacs", departmentSlug: "jura", departmentName: "Jura", intro: "Une station lacustre familiale avec plages aménagées et activités nautiques.", idealFor: "Les familles souhaitant placer la baignade en lac au centre des vacances.", nearby: ["Grand Lac de Clairvaux", "Lac de Vouglans", "Cascades du Hérisson"], practical: ["Arriver tôt sur les plages en été", "Vérifier les zones de baignade", "Température plus fraîche le soir"] },
  { slug: "pont-de-poitte", name: "Pont-de-Poitte", departmentSlug: "jura", departmentName: "Jura", intro: "Un village traversé par l’Ain, proche des marmites de géant et du lac de Vouglans.", idealFor: "Les amateurs de pêche, de rivière et d’excursions nature.", nearby: ["Marmites de géant", "Lac de Vouglans", "Clairvaux-les-Lacs"], practical: ["Respecter les zones de baignade", "Voiture recommandée", "Prévoir chaussures d’eau et de marche"] },
  { slug: "maupertus-sur-mer", name: "Maupertus-sur-Mer", departmentSlug: "manche", departmentName: "Manche", intro: "Une commune côtière du Cotentin, entre falaises, petites plages et proximité de Cherbourg.", idealFor: "Les voyageurs qui recherchent une Normandie maritime et plus sauvage.", nearby: ["Cherbourg-en-Cotentin", "Barfleur", "Phare de Gatteville"], practical: ["Consulter les horaires de marée", "Prévoir une veste imperméable", "Voiture utile pour parcourir le Cotentin"] },
  { slug: "genets", name: "Genêts", departmentSlug: "manche", departmentName: "Manche", intro: "Un village de la baie du Mont-Saint-Michel connu pour ses panoramas et traversées guidées.", idealFor: "Ceux qui veulent vivre la baie au rythme des marées et des grands paysages.", nearby: ["Bec d’Andaine", "Mont-Saint-Michel", "Avranches"], practical: ["Ne jamais traverser la baie sans guide", "Vérifier les horaires de marée", "Réserver les sorties en saison"] },
  { slug: "beauvoir", name: "Beauvoir", departmentSlug: "manche", departmentName: "Manche", intro: "À quelques kilomètres du Mont-Saint-Michel, une base très pratique pour visiter le site tôt ou tard dans la journée.", idealFor: "Les familles qui font du Mont-Saint-Michel la visite principale du séjour.", nearby: ["Mont-Saint-Michel", "Moulin de Moidrey", "Pontorson"], practical: ["Visiter avant 10 h ou en soirée", "Anticiper le coût du stationnement", "La côte du Cotentin demande davantage de route"] },
];

export const cityGuides = Object.fromEntries(
  guides.map((guide) => [`${guide.departmentSlug}/${guide.slug}`, guide]),
) as Record<string, CityGuide>;

export function getCityGuidesForDepartment(departmentSlug: string) {
  return guides.filter((guide) => guide.departmentSlug === departmentSlug);
}
