import { moreSuncampOffers } from "@/lib/moreSuncampOffers";
import { expandedSuncampOffers } from "@/lib/expandedCampingData";

export type SuncampOffer = {
  id: string;
  name: string;
  city: string;
  stars?: number;
  rating?: number;
  image: string;
  href: string;
  summary: string;
  highlights: string[];
  distanceToSeaKm?: number;
};

// Sélection éditoriale issue du flux produit Suncamp #1529348,
// mis à jour quotidiennement par TradeTracker. Contrôle : 3 septembre 2026.
export const suncampVarOffers: SuncampOffer[] = [
  ...(expandedSuncampOffers.var ?? []),
  {
    id: "104404",
    name: "Camping Yelloh! Village Holiday Green",
    city: "Fréjus",
    stars: 5,
    image: "https://cdn.acsi.eu/6/9/4/4/6944539334310.jpg",
    href: "https://www.suncamp.fr/tradetracker/?tt=11662_1529348_515442_&r=https%3A%2F%2Fwww.suncamp.fr%2Ffrance%2Fprovence-alpes-cote-dazur%2Fvar%2Ffrejus%2Fcamping-yelloh-village-holiday-green-104404%2F",
    summary: "Un grand camping familial connu pour son parc aquatique et ses nombreuses animations.",
    highlights: ["Parc aquatique", "Animations", "Bien-être"],
    distanceToSeaKm: 7,
  },
  {
    id: "104405",
    name: "Camping Sandaya Domaine du Colombier",
    city: "Fréjus",
    stars: 5,
    rating: 7,
    image: "https://cdn.acsi.eu/6/9/6/1/69612a18162d6.jpg",
    href: "https://www.suncamp.fr/tradetracker/?tt=11662_1529348_515442_&r=https%3A%2F%2Fwww.suncamp.fr%2Ffrance%2Fprovence-alpes-cote-dazur%2Fvar%2Ffrejus%2Fcamping-sandaya-domaine-du-colombier-104405%2F",
    summary: "Un domaine haut de gamme avec vaste espace aquatique, clubs enfants et centre de bien-être.",
    highlights: ["Lagon", "Clubs enfants", "Spa"],
    distanceToSeaKm: 4.5,
  },
  {
    id: "104410",
    name: "Camping Sandaya Étoile d’Argens",
    city: "Saint-Aygulf",
    stars: 5,
    image: "https://cdn.acsi.eu/6/7/e/f/67efafd8d64b6.jpg",
    href: "https://www.suncamp.fr/tradetracker/?tt=11662_1529348_515442_&r=https%3A%2F%2Fwww.suncamp.fr%2Ffrance%2Fprovence-alpes-cote-dazur%2Fvar%2Fsaint-aygulf%2Fcamping-sandaya-etoile-dargens-104410%2F",
    summary: "Une adresse familiale entre vignobles, parc aquatique et plages de Saint-Aygulf.",
    highlights: ["Piscines", "Mini-clubs", "Navette plage"],
    distanceToSeaKm: 3.5,
  },
  {
    id: "104409",
    name: "Camping Sandaya Douce Quiétude",
    city: "Saint-Raphaël",
    stars: 5,
    rating: 7.9,
    image: "https://cdn.acsi.eu/6/8/7/f/687fa5070d586.jpg",
    href: "https://www.suncamp.fr/tradetracker/?tt=11662_1529348_515442_&r=https%3A%2F%2Fwww.suncamp.fr%2Ffrance%2Fprovence-alpes-cote-dazur%2Fvar%2Fsaint-raphael%2Fcamping-sandaya-douce-quietude-104409%2F",
    summary: "Au pied de l’Estérel, avec parc aquatique surveillé et navette vers les plages.",
    highlights: ["Parc aquatique", "Estérel", "Navette plage"],
    distanceToSeaKm: 5,
  },
  {
    id: "108484",
    name: "Esterel Caravaning",
    city: "Agay",
    stars: 5,
    image: "https://cdn.acsi.eu/6/a/8/c/6a8c04dca2b29.jpg",
    href: "https://www.suncamp.fr/tradetracker/?tt=11662_1529348_515442_&r=https%3A%2F%2Fwww.suncamp.fr%2Ffrance%2Fprovence-alpes-cote-dazur%2Fvar%2Fagay%2Festerel-caravaning-108484%2F",
    summary: "Un camping spacieux entre le massif rouge de l’Estérel et la baie d’Agay.",
    highlights: ["Cinq piscines", "Randonnée", "Espace bien-être"],
    distanceToSeaKm: 3.5,
  },
  {
    id: "108496",
    name: "Camping Leï Suves",
    city: "Roquebrune-sur-Argens",
    stars: 4,
    rating: 7.7,
    image: "https://cdn.acsi.eu/6/9/d/9/69d91adbc9d02.jpg",
    href: "https://www.suncamp.fr/tradetracker/?tt=11662_1529348_515442_&r=https%3A%2F%2Fwww.suncamp.fr%2Ffrance%2Fprovence-alpes-cote-dazur%2Fvar%2Froquebrune-sur-argens%2Fcamping-lei-suves-108496%2F",
    summary: "Une option plus calme dans un décor provençal, avec piscine et hébergements glamping.",
    highlights: ["Cadre calme", "Piscine", "Glamping"],
  },
];

const baseSuncampOffersByDepartment: Record<string, SuncampOffer[]> = {
  ...moreSuncampOffers,
  vendee: [
    {
      id: "100366",
      name: "Camping Sandaya Le Littoral",
      city: "Talmont-Saint-Hilaire",
      stars: 5,
      rating: 8,
      image: "https://cdn.acsi.eu/6/a/5/4/6a54df600fb57.jpg",
      href: "https://www.suncamp.fr/tradetracker/?tt=11662_1529348_515442_&r=https%3A%2F%2Fwww.suncamp.fr%2Ffrance%2Fpays-de-la-loire%2Fvendee%2Ftalmont-saint-hilaire%2Fcamping-sandaya-le-littoral-100366%2F",
      summary: "Un camping familial de la Côte de Lumière avec accès à l’océan par un sentier.",
      highlights: ["Océan", "Parc aquatique", "Animations"],
      distanceToSeaKm: 0.1,
    },
    {
      id: "103360",
      name: "Camping Village de la Guyonnière",
      city: "Saint-Julien-des-Landes",
      stars: 5,
      rating: 7,
      image: "https://cdn.acsi.eu/6/9/d/c/69dcca3cdbcb0.jpg",
      href: "https://www.suncamp.fr/tradetracker/?tt=11662_1529348_515442_&r=https%3A%2F%2Fwww.suncamp.fr%2Ffrance%2Fpays-de-la-loire%2Fvendee%2Fsaint-julien-des-landes%2Fcamping-village-de-la-guyonniere-103360%2F",
      summary: "Un vaste domaine verdoyant au bord du lac du Jaunay, à environ dix minutes de la mer en voiture.",
      highlights: ["Lac du Jaunay", "Parc aquatique", "Domaine verdoyant"],
      distanceToSeaKm: 10,
    },
    {
      id: "109870",
      name: "Flower Camping Les Dunes",
      city: "Longeville-sur-Mer",
      stars: 4,
      image: "https://cdn.acsi.eu/6/9/5/f/695f943d095c6.jpg",
      href: "https://www.suncamp.fr/tradetracker/?tt=11662_1529348_515442_&r=https%3A%2F%2Fwww.suncamp.fr%2Ffrance%2Fpays-de-la-loire%2Fvendee%2Flongeville-sur-mer%2Fflower-camping-les-dunes-109870%2F",
      summary: "Une adresse dans la pinède, proche de la grande plage des Conches.",
      highlights: ["Pinède", "Piscine chauffée", "Plage des Conches"],
      distanceToSeaKm: 1,
    },
    {
      id: "111515",
      name: "Camping Sandaya La Grande Côte",
      city: "La Barre-de-Monts",
      stars: 4,
      rating: 8.1,
      image: "https://cdn.acsi.eu/6/9/4/0/6940366989ce8.jpg",
      href: "https://www.suncamp.fr/tradetracker/?tt=11662_1529348_515442_&r=https%3A%2F%2Fwww.suncamp.fr%2Ffrance%2Fpays-de-la-loire%2Fvendee%2Fla-barre-de-monts%2Fcamping-sandaya-la-grande-cote-111515%2F",
      summary: "Un camping boisé près de Fromentine, entre dunes, plage et marais.",
      highlights: ["Plage", "Forêt", "Proche de Noirmoutier"],
      distanceToSeaKm: 0.1,
    },
  ],
  herault: [
    {
      id: "121352",
      name: "Camping Mas des Lavandes",
      city: "Sérignan",
      stars: 4,
      rating: 7.7,
      image: "https://cdn.acsi.eu/6/7/e/f/67efc653b7b61.jpg",
      href: "https://www.suncamp.fr/tradetracker/?tt=11662_1529348_515442_&r=https%3A%2F%2Fwww.suncamp.fr%2Ffrance%2Flanguedoc-roussillon%2Fherault%2Fserignan%2Fcamping-mas-des-lavandes-121352%2F",
      summary: "Une option familiale entre grand espace aquatique et plage de Valras.",
      highlights: ["Piscines", "Animations", "Proche de Valras"],
      distanceToSeaKm: 1.5,
    },
    {
      id: "104021",
      name: "Camping Sandaya Domaine de la Dragonnière",
      city: "Vias",
      stars: 5,
      rating: 8.5,
      image: "https://cdn.acsi.eu/6/a/6/7/6a6765682b9c8.jpg",
      href: "https://www.suncamp.fr/tradetracker/?tt=11662_1529348_515442_&r=https%3A%2F%2Fwww.suncamp.fr%2Ffrance%2Flanguedoc-roussillon%2Fherault%2Fvias%2Fcamping-sandaya-domaine-de-la-dragonniere-104021%2F",
      summary: "Un grand domaine haut de gamme à Vias, centré sur les plaisirs aquatiques et les services.",
      highlights: ["Espace aquatique", "Spa", "Clubs enfants"],
      distanceToSeaKm: 6,
    },
    {
      id: "104006",
      name: "Camping Sandaya Les Tamaris",
      city: "Aresquiers",
      stars: 5,
      rating: 6.8,
      image: "https://cdn.acsi.eu/6/a/5/7/6a5791a31112a.jpg",
      href: "https://www.suncamp.fr/tradetracker/?tt=11662_1529348_515442_&r=https%3A%2F%2Fwww.suncamp.fr%2Ffrance%2Flanguedoc-roussillon%2Fherault%2Faresquies%2Fcamping-sandaya-les-tamaris-104006%2F",
      summary: "Un camping verdoyant entre la Méditerranée et l’étang d’Ingril, au sud de Montpellier.",
      highlights: ["Accès mer", "Piscine", "Près de Montpellier"],
      distanceToSeaKm: 0,
    },
    {
      id: "104036",
      name: "Camping Sandaya Les Vagues",
      city: "Valras-Plage",
      stars: 4,
      rating: 7.9,
      image: "https://cdn.acsi.eu/6/9/5/8/6958eb46ae3a0.jpg",
      href: "https://www.suncamp.fr/tradetracker/?tt=11662_1529348_515442_&r=https%3A%2F%2Fwww.suncamp.fr%2Ffrance%2Flanguedoc-roussillon%2Fherault%2Fvalras-plage%2Fcamping-sandaya-les-vagues-104036%2F",
      summary: "Un grand camping animé à quelques minutes à pied de la plage de Valras.",
      highlights: ["Plage", "Sports", "Clubs enfants"],
      distanceToSeaKm: 0.5,
    },
  ],
  landes: [
    {
      id: "100507",
      name: "Camping Sandaya Le Col Vert",
      city: "Vielle-Saint-Girons",
      stars: 4,
      rating: 7.9,
      image: "https://cdn.acsi.eu/6/a/5/4/6a54ee939d73d.jpg",
      href: "https://www.suncamp.fr/tradetracker/?tt=11662_1529348_515442_&r=https%3A%2F%2Fwww.suncamp.fr%2Ffrance%2Faquitaine%2Flandes%2Fvielle-saint-girons%2Fcamping-sandaya-le-col-vert-100507%2F",
      summary: "Un camping dans la forêt, au bord du lac de Léon, pour alterner baignade et sports nautiques.",
      highlights: ["Lac de Léon", "Piscines", "Sports nautiques"],
      distanceToSeaKm: 8,
    },
    {
      id: "100987",
      name: "Camping Sandaya Sanguinet Plage",
      city: "Sanguinet",
      stars: 5,
      image: "https://cdn.acsi.eu/6/9/4/4/694414a32d944.jpg",
      href: "https://www.suncamp.fr/tradetracker/?tt=11662_1529348_515442_&r=https%3A%2F%2Fwww.suncamp.fr%2Ffrance%2Faquitaine%2Flandes%2Fsanguinet%2Fcamping-sandaya-sanguinet-plage-100987%2F",
      summary: "Un cinq étoiles au bord du lac de Sanguinet, entre Biscarrosse et le bassin d’Arcachon.",
      highlights: ["Plage du lac", "Parc aquatique", "Pinède"],
    },
    {
      id: "103479",
      name: "Village Resort & Spa Le Vieux Port",
      city: "Messanges",
      stars: 5,
      image: "https://cdn.acsi.eu/6/9/0/b/690b20285f1c6.jpg",
      href: "https://www.suncamp.fr/tradetracker/?tt=11662_1529348_515442_&r=https%3A%2F%2Fwww.suncamp.fr%2Ffrance%2Faquitaine%2Flandes%2Fmessanges%2Fcamp-village-resort-spa-le-vieux-port-103479%2F",
      summary: "Un grand resort dans la forêt landaise, avec accès rapide à la plage Atlantique.",
      highlights: ["Accès plage", "Sept piscines", "Spa"],
      distanceToSeaKm: 0.5,
    },
    {
      id: "121355",
      name: "Camping Sandaya Soustons Village",
      city: "Soustons",
      stars: 5,
      rating: 7.8,
      image: "https://cdn.acsi.eu/6/a/5/6/6a56092f91bd0.jpg",
      href: "https://www.suncamp.fr/tradetracker/?tt=11662_1529348_515442_&r=https%3A%2F%2Fwww.suncamp.fr%2Ffrance%2Faquitaine%2Flandes%2Fsoustons%2Fcamping-sandaya-soustons-village-121355%2F",
      summary: "Un village de locations sous les pins, entre océan, lacs et forêt landaise.",
      highlights: ["Sans voitures", "Piscine à vagues", "Bien-être"],
      distanceToSeaKm: 6,
    },
  ],
  "charente-maritime": [
    {
      id: "100388",
      name: "Camping Sandaya L’Estanquet",
      city: "Les Mathes",
      stars: 4,
      image: "https://cdn.acsi.eu/6/a/8/c/6a8c45c875896.jpg",
      href: "https://www.suncamp.fr/tradetracker/?tt=11662_1529348_515442_&r=https%3A%2F%2Fwww.suncamp.fr%2Ffrance%2Fpoitou-charentes%2Fcharente-maritime%2Fles-mathes%2Fcamping-sandaya-lestanquet-100388%2F",
      summary: "Une adresse familiale à La Palmyre avec un vaste espace de piscines chauffées.",
      highlights: ["Piscines chauffées", "La Palmyre", "Familles"],
      distanceToSeaKm: 4,
    },
    {
      id: "103420",
      name: "Camping Sandaya L’Orée du Bois",
      city: "Les Mathes",
      stars: 5,
      rating: 8.1,
      image: "https://cdn.acsi.eu/6/a/5/4/6a54f6f8d8560.jpg",
      href: "https://www.suncamp.fr/tradetracker/?tt=11662_1529348_515442_&r=https%3A%2F%2Fwww.suncamp.fr%2Ffrance%2Fpoitou-charentes%2Fcharente-maritime%2Fles-mathes%2Fcamping-sandaya-loree-du-bois-103420%2F",
      summary: "Un cinq étoiles dans la pinède de La Coubre, entre Royan et l’île d’Oléron.",
      highlights: ["Pinède", "Espace aquatique", "Près de La Palmyre"],
      distanceToSeaKm: 4,
    },
    {
      id: "108789",
      name: "Camping Sandaya Séquoia Parc",
      city: "Saint-Just-Luzac",
      stars: 5,
      rating: 7.9,
      image: "https://cdn.acsi.eu/6/a/5/7/6a576078815c5.jpg",
      href: "https://www.suncamp.fr/tradetracker/?tt=11662_1529348_515442_&r=https%3A%2F%2Fwww.suncamp.fr%2Ffrance%2Fpoitou-charentes%2Fcharente-maritime%2Fsaint-just-luzac%2Fcamping-sandaya-sequoia-parc-108789%2F",
      summary: "Un vaste domaine autour d’un ancien château, près de l’île d’Oléron.",
      highlights: ["Domaine de 45 ha", "Ancien château", "Proche océan"],
      distanceToSeaKm: 7,
    },
    {
      id: "116528",
      name: "Camping Sandaya Amis de la Plage",
      city: "Le Bois-Plage-en-Ré",
      stars: 4,
      rating: 6.2,
      image: "https://cdn.acsi.eu/6/9/6/4/6964f276575c1.jpg",
      href: "https://www.suncamp.fr/tradetracker/?tt=11662_1529348_515442_&r=https%3A%2F%2Fwww.suncamp.fr%2Ffrance%2Fpoitou-charentes%2Fcharente-maritime%2Fle-bois-plage-en-re%2Fcamping-sandaya-amis-de-la-plage-116528%2F",
      summary: "Un camping sur l’île de Ré avec la plage de sable à proximité immédiate, mais sans piscine.",
      highlights: ["Île de Ré", "Accès plage", "Animations"],
      distanceToSeaKm: 0.1,
    },
  ],
};

export const suncampOffersByDepartment: Record<string, SuncampOffer[]> = Object.fromEntries(
  Array.from(new Set([...Object.keys(baseSuncampOffersByDepartment), ...Object.keys(expandedSuncampOffers)]))
    .map((department) => [
      department,
      [...(baseSuncampOffersByDepartment[department] ?? []), ...(expandedSuncampOffers[department] ?? [])],
    ]),
);
